name: my_first_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.4.0

  # HTTP & API
  dio: ^5.3.0

  # Google Sign-In
  google_sign_in: ^6.1.0

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Localization
  intl: ^0.20.2

  # State Management Alternative
  provider: ^6.0.0

  # Connectivity
  connectivity_plus: ^5.0.2
  excel: ^4.0.6

  # Animations
  loading_animation_widget: ^1.2.0
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/localization/en.json
    - assets/localization/te.json
    - assets/localization/hi.json
    - assets/milestones/problem_a_milestones.json
    - assets/images/
    - backend/data/boys_wfa.csv
    - backend/data/girls_wfa.csv
    - backend/data/boys_hfa.csv
    - backend/data/girls_hfa.csv
